name: Go Build
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v2
    - id: date
      run: echo "::set-output name=value::$(date +%FT%TZ)"
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.17
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: |
          -X github.com/prometheus/common/version.Version=${{ github.event.release.tag_name }}
          -X github.com/prometheus/common/version.Revision=${{ github.sha }}
          -X github.com/prometheus/common/version.Branch=${{ github.ref }}
          -X github.com/prometheus/common/version.BuildDate=${{ steps.date.outputs.value }}
          -X github.com/prometheus/common/version.BuildUser=github-actions
