name: Builds and Tests
on: [pull_request]
jobs:
  checks:
    name: Builds and Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Test Docker build
      run: docker build .
